// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcdzNV4627CM5dc3vApEDAXwlkrSQjwG0',
    appId: '1:476412967773:web:25450f0ec3b8cac18786b4',
    messagingSenderId: '476412967773',
    projectId: 'mental-be228',
    authDomain: 'mental-be228.firebaseapp.com',
    storageBucket: 'mental-be228.firebasestorage.app',
    measurementId: 'G-9MKZ41QR23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTMXtWnfvY_ijOBY_mvoF-OlUXiPECTk',
    appId: '1:476412967773:android:e1b4f9f7131f15f18786b4',
    messagingSenderId: '476412967773',
    projectId: 'mental-be228',
    storageBucket: 'mental-be228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC51e2ZXCeFSIn5bnMhLjN2YXBAo6xijN4',
    appId: '1:476412967773:ios:e060e3ab9429b1d68786b4',
    messagingSenderId: '476412967773',
    projectId: 'mental-be228',
    storageBucket: 'mental-be228.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC51e2ZXCeFSIn5bnMhLjN2YXBAo6xijN4',
    appId: '1:476412967773:ios:e060e3ab9429b1d68786b4',
    messagingSenderId: '476412967773',
    projectId: 'mental-be228',
    storageBucket: 'mental-be228.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcdzNV4627CM5dc3vApEDAXwlkrSQjwG0',
    appId: '1:476412967773:web:8fcf7cab966489ef8786b4',
    messagingSenderId: '476412967773',
    projectId: 'mental-be228',
    authDomain: 'mental-be228.firebaseapp.com',
    storageBucket: 'mental-be228.firebasestorage.app',
    measurementId: 'G-T106GWL54Y',
  );

}